### 获取用户8088信息1个参数
POST http://localhost:8088/findById?id=1


### 获取用户信息1个参数
POST http://localhost:8082/
Content-Type: application/json

{
  "service": "cn.cutie.clotrpc.demo.api.UserService",
  "methodSign": "findById@1_int",
  "args": [100]
}

### 获取用户信息2个参数
POST http://localhost:8080/
Content-Type: application/json

{
  "service": "cn.cutie.clotrpc.demo.api.UserService",
  "methodSign": "findById@2_int_java.lang.String",
  "args": [100, "Sleep-"]
}

### mock
POST http://localhost:8080/
Content-Type: application/json

{
  "service": "cn.cutie.clotrpc.demo.api.UserService",
  "methodSign": "toString",
  "args": []
}

### 获取订单信息
POST http://localhost:8080/
Content-Type: application/json

{
  "service": "cn.cutie.clotrpc.demo.api.OrderService",
  "methodSign": "findById@1_java.lang.Integer",
  "args": [200]
}

###
